DISTANCE_NARROW=1.2
DISTANCE_WIDE=1.5
DISCOUNT=30
DISCOUNT_PROM=20
CAR_UNIT_PRICE=5.20
BIKE_UNIT_PRICE=1.70
SCOOTER_UNIT_PRICE=0.40
FILE_RENTALS=PJ2 - projektni zadatak 2024 - Iznajmljivanja.csv
FILE_VEHICLES=PJ2 - projektni zadatak 2024 - Prevozna sredstva.csv
FILE_RECEIPTHEADER=racun-zaglavlje.txt
FILE_RECEIPTSEP=racun-separator.txt
RECEIPT_FILES_PATH:Racuni
FILES_SERIALIZATION=Serijalizacija
FILE_SERIALIZATION_CAR=car.ser
FILE_SERIALIZATION_BIKE=bike.ser
FILE_SERIALIZATION_SCOOTER=scooter.ser